# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('time_of_publishing', models.DateTimeField(blank=True, verbose_name='Дата добавления')),
                ('time_of_editing', models.DateTimeField(blank=True, verbose_name='Дата изменения')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfc.Image', verbose_name='Изображение')),
            ],
        ),
    ]
