# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0003_auto_20170212_2220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List_of_requests',
            new_name='List_of_request',
        ),
    ]
