# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0005_auto_20170212_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='picture',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mfc.Image'),
        ),
    ]
