# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0007_auto_20170212_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfc.User'),
        ),
    ]
