# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0008_auto_20170215_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='login',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
