# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mfc', '0010_auto_20170319_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_of_request',
            name='request',
        ),
        migrations.RemoveField(
            model_name='user',
            name='snils',
        ),
        migrations.AddField(
            model_name='passport',
            name='sex',
            field=models.CharField(choices=[('мужской', 'муж.'), ('женский', 'жен.')], default='мужской', max_length=4),
        ),
        migrations.AddField(
            model_name='snils',
            name='login',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='picture',
            field=models.ImageField(upload_to='documents/', verbose_name='Фото документа'),
        ),
        migrations.AlterField(
            model_name='request',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='List_of_request',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
