# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0012_auto_20170410_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='participant_three',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_three', to='mfc.Document'),
        ),
        migrations.AlterField(
            model_name='request',
            name='participant_two',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_two', to='mfc.Document'),
        ),
    ]
