# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0013_auto_20170410_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_of_adding',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
