# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0014_document_date_of_adding'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='participant_eight',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_eight', to='mfc.Document'),
        ),
        migrations.AddField(
            model_name='request',
            name='participant_fife',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_fife', to='mfc.Document'),
        ),
        migrations.AddField(
            model_name='request',
            name='participant_four',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_four', to='mfc.Document'),
        ),
        migrations.AddField(
            model_name='request',
            name='participant_nine',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_nine', to='mfc.Document'),
        ),
        migrations.AddField(
            model_name='request',
            name='participant_seven',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_seven', to='mfc.Document'),
        ),
        migrations.AddField(
            model_name='request',
            name='participant_six',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_six', to='mfc.Document'),
        ),
        migrations.AddField(
            model_name='request',
            name='participant_ten',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_ten', to='mfc.Document'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('подана', 'подана'), ('обрабатывается', 'обрабатывается'), ('завершена', 'завершена')], default='подана', max_length=14),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_of_beginning',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
