# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0015_auto_20170410_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='participant_fife',
        ),
        migrations.AddField(
            model_name='request',
            name='participant_five',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_five', to='mfc.Document'),
        ),
    ]
