# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0016_auto_20170410_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='sex',
            field=models.CharField(choices=[('мужской', 'муж.'), ('женский', 'жен.')], default='мужской', max_length=7),
        ),
    ]
