# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mfc', '0017_auto_20170411_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField(blank=True, default=None, max_length=11, null=True, verbose_name='Номер телефона')),
                ('post', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('snils_number', models.CharField(max_length=11, unique=True, verbose_name='Серийный номер')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='snils',
            name='login',
        ),
        migrations.AddField(
            model_name='passport',
            name='code',
            field=models.PositiveIntegerField(default=1, max_length=6, verbose_name='Код подразделения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passport',
            name='serial_number',
            field=models.PositiveIntegerField(max_length=10, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.DeleteModel(
            name='Snils',
        ),
    ]
