# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0018_auto_20170501_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='post',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
    ]
